### ISSUE TITLE
Ban IP

### ISSUE THREAD

**Issue by DavyArt** [ProCompTEAM/Game#4]
**Баг з АЙПІ, нада виправити, памагите**

**Comment by GlebKachanouski** [comment]
#51 Fixed

**Comment by GlebKachanouski** [comment]
#81af3b4

**Comment by GlebKachanouski** [comment]
[https://github.com/ProCompTEAM/Game/commit/81af3b4b90a5f8ca15861139ad8cd25a7fcb8577](url)

**Comment by GlebKachanouski** [comment]
fixed #81af3b4

**Comment by GlebKachanouski** [comment]
fixed #81af3b4

**Comment by GlebKachanouski** [comment]
fixed #81af3b4
